version: "3"
services:
  mysql:
    # 컨테이너 이름을 주고 싶다면 작성한다
    # container_name: test_database
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: clg_db
      MYSQL_ROOT_PASSWORD: 1886
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: on-failure
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql