version: "3"
services:
  mysql:
    # 컨테이너 이름을 주고 싶다면 작성한다
    # container_name: test_database
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 5001
    ports:
      - "5001:5001"
    depends_on:
      - mysql