spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clg_db?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: PARK
    password: 1024

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml